version: '3.8'
services:
  web:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app:ro
      - ./data:/app/data
    ports:
      - "5081:5081"
    env_file:
      - .env
    command: npm start